import { Kumbh_Sans } from "next/font/google";
import "./globals.css";

const font = Kumbh_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
  icons: "/favicon-32x32.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
